const Languages = [
  { id: "0", name: "af-ZA" },
  { id: "1", name: "ar-AE" },
  { id: "2", name: "ar-SA" },
  { id: "3", name: "be-BY" },
  { id: "4", name: "bg-BG" },
  { id: "5", name: "bn-BD" },
  { id: "6", name: "ca-ES" },
  { id: "7", name: "ch-GU" },
  { id: "8", name: "cn-CN" },
  { id: "9", name: "cs-CZ" },
  { id: "10", name: "cy-GB" },
  { id: "11", name: "da-DK" },
  { id: "12", name: "de-AT" },
  { id: "13", name: "de-CH" },
  { id: "14", name: "de-DE" },
  { id: "15", name: "el-GR" },
  { id: "16", name: "en-AU" },
  { id: "17", name: "en-CA" },
  { id: "18", name: "en-GB" },
  { id: "19", name: "en-IE" },
  { id: "20", name: "en-NZ" },
  { id: "21", name: "en-US" },
  { id: "22", name: "eo-EO" },
  { id: "23", name: "es-ES" },
  { id: "24", name: "es-MX" },
  { id: "25", name: "et-EE" },
  { id: "26", name: "eu-ES" },
  { id: "27", name: "fa-IR" },
  { id: "28", name: "fi-FI" },
  { id: "29", name: "fr-CA" },
  { id: "30", name: "fr-FR" },
  { id: "31", name: "ga-IE" },
  { id: "32", name: "gd-GB" },
  { id: "33", name: "gl-ES" },
  { id: "34", name: "he-IL" },
  { id: "35", name: "hi-IN" },
  { id: "36", name: "hr-HR" },
  { id: "37", name: "hu-HU" },
  { id: "38", name: "id-ID" },
  { id: "39", name: "it-IT" },
  { id: "40", name: "ja-JP" },
  { id: "41", name: "ka-GE" },
  { id: "42", name: "kk-KZ" },
  { id: "43", name: "kn-IN" },
  { id: "44", name: "ko-KR" },
  { id: "45", name: "ky-KG" },
  { id: "46", name: "lt-LT" },
  { id: "47", name: "lv-LV" },
  { id: "48", name: "ml-IN" },
  { id: "49", name: "mr-IN" },
  { id: "50", name: "ms-MY" },
  { id: "51", name: "ms-SG" },
  { id: "52", name: "nb-NO" },
  { id: "53", name: "nl-BE" },
  { id: "54", name: "nl-NL" },
  { id: "55", name: "no-NO" },
  { id: "56", name: "pa-IN" },
  { id: "57", name: "pl-PL" },
  { id: "58", name: "pt-BR" },
  { id: "59", name: "pt-PT" },
  { id: "60", name: "ro-RO" },
  { id: "61", name: "ru-RU" },
  { id: "62", name: "si-LK" },
  { id: "63", name: "sk-SK" },
  { id: "64", name: "sl-SI" },
  { id: "65", name: "sq-AL" },
  { id: "66", name: "sr-RS" },
  { id: "67", name: "sv-SE" },
  { id: "68", name: "ta-IN" },
  { id: "69", name: "te-IN" },
  { id: "70", name: "th-TH" },
  { id: "71", name: "tl-PH" },
  { id: "72", name: "tr-TR" },
  { id: "73", name: "uk-UA" },
  { id: "74", name: "vi-VN" },
  { id: "75", name: "zh-CN" },
  { id: "76", name: "zh-HK" },
  { id: "77", name: "zh-SG" },
  { id: "78", name: "zh-TW" },
  { id: "79", name: "zu-ZA" },
];
export default Languages;
/* let obj = [];
const array = [
  "af-ZA",
  "ar-AE",
  "ar-SA",
  "be-BY",
  "bg-BG",
  "bn-BD",
  "ca-ES",
  "ch-GU",
  "cn-CN",
  "cs-CZ",
  "cy-GB",
  "da-DK",
  "de-AT",
  "de-CH",
  "de-DE",
  "el-GR",
  "en-AU",
  "en-CA",
  "en-GB",
  "en-IE",
  "en-NZ",
  "en-US",
  "eo-EO",
  "es-ES",
  "es-MX",
  "et-EE",
  "eu-ES",
  "fa-IR",
  "fi-FI",
  "fr-CA",
  "fr-FR",
  "ga-IE",
  "gd-GB",
  "gl-ES",
  "he-IL",
  "hi-IN",
  "hr-HR",
  "hu-HU",
  "id-ID",
  "it-IT",
  "ja-JP",
  "ka-GE",
  "kk-KZ",
  "kn-IN",
  "ko-KR",
  "ky-KG",
  "lt-LT",
  "lv-LV",
  "ml-IN",
  "mr-IN",
  "ms-MY",
  "ms-SG",
  "nb-NO",
  "nl-BE",
  "nl-NL",
  "no-NO",
  "pa-IN",
  "pl-PL",
  "pt-BR",
  "pt-PT",
  "ro-RO",
  "ru-RU",
  "si-LK",
  "sk-SK",
  "sl-SI",
  "sq-AL",
  "sr-RS",
  "sv-SE",
  "ta-IN",
  "te-IN",
  "th-TH",
  "tl-PH",
  "tr-TR",
  "uk-UA",
  "vi-VN",
  "zh-CN",
  "zh-HK",
  "zh-SG",
  "zh-TW",
  "zu-ZA",
];
const convertArray = (array) => {
  if (array.length === 0) {
    return "no found data";
  } else {
    Object.keys(array).forEach((key) => {
      obj.push({
        name: array[key],
      });
    });
    return obj;
  }
};
console.log(convertArray(array));

export default convertArray;
 */
